// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlZFctpddNmG3e5ZVvby24t7JenP0HEf0',
    appId: '1:1066069707693:web:21a95fef85431f903eaf24',
    messagingSenderId: '1066069707693',
    projectId: 'soap-4f8dc',
    authDomain: 'soap-4f8dc.firebaseapp.com',
    storageBucket: 'soap-4f8dc.firebasestorage.app',
    measurementId: 'G-79BRVGVS50',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEbaAHNQtIC4GzGRXUpfEwmaXvwtKUYlU',
    appId: '1:1066069707693:android:e045cf6d686ce8f33eaf24',
    messagingSenderId: '1066069707693',
    projectId: 'soap-4f8dc',
    storageBucket: 'soap-4f8dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBQRku_dOI3UuSy_TdM4kssXo_TiBWtSQ',
    appId: '1:1066069707693:ios:070af8a561af06fb3eaf24',
    messagingSenderId: '1066069707693',
    projectId: 'soap-4f8dc',
    storageBucket: 'soap-4f8dc.firebasestorage.app',
    iosBundleId: 'com.soap.practitioner',
  );

}